diff --git a/src/Makefile b/src/Makefile
index ad6622f..ad0c9a4 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -1,13 +1,11 @@
-LUA     = lua-5.1.4
-#LUA     = lua-5.2.0
-CFLAGS  = -fno-exceptions -fno-rtti -O2 -I$(LUA) -L$(LUA)
+CC ?= gcc
+CXX ?= g++
+
 SRC     = main.cpp soap.cpp mem.cpp mcast.cpp luaxlib.cpp luaxcore.cpp luajson.cpp luajson_parser.cpp
 
 x86:
-	make -C $(LUA) CC=gcc a
-	gcc -O2 -c -o md5.o md5c.c
-	gcc $(CFLAGS) -DWITH_LIBUUID -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -o xupnpd $(SRC) md5.o -llua -ldl -lm -luuid
-	strip xupnpd
+	$(CC) $(CFLAGS) -c -o md5.o md5c.c
+	$(CXX) $(CXXFLAGS) $(LDFLAGS) -fno-exceptions -fno-rtti -DWITH_LIBUUID -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -o xupnpd $(SRC) md5.o -llua -ldl -lm -luuid
 
 x86_bsd:
 	make -C $(LUA) CC=gcc a
